name: Cloudability Governance Test
run-name: Deployment Run
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  cloudability-governance:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE }} 
          role-session-name: ${{ github.run_id }} 

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          terraform_wrapper: false

      - name: Generate tfplan in the prod directory
        id: tf
        run: |
          terraform init
          terraform plan -refresh=false -lock=false -input=false -out=tfplan
          terraform show -json tfplan > tfplan.json
     
      - name: Redact secrets from tfplan
        run: |
          sed -i 's/"password":"[^"]*"/"password":""/g' tfplan.json
          sed -i 's/"secret_string":"{[^}]*}"/"secret_string":""/g' tfplan.json


      # check if usage.json file exists
      - name: find usage.json
        id: usage
        run: |
          if [ -f usage.json ]; then
            echo "USAGE_PATH=usage.json" >> "$GITHUB_OUTPUT"
          else
            echo "USAGE_PATH=" >> "$GITHUB_OUTPUT"
          fi

      - name: Get Frontdoor token
        uses: IBM/ibm-cloudability-governance/actions/frontdoor/login@v0.2.x
        with:
          fd-url: ${{ vars.FD_URL }}
          fd-public-key: ${{ secrets.FD_PUBLIC_KEY }}
          fd-secret-key: ${{ secrets.FD_SECRET_KEY }}

      - name: Get GitHub PR metadata
        uses: IBM/ibm-cloudability-governance/actions/github-info@v0.2.x
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}

      - name: Run Cloudability Governance Metadata Retrieval
        uses: IBM/ibm-cloudability-governance/actions/metadata@v0.2.x
        with:
          cloudability-host: ${{ vars.CLDY_HOST }}
          fd-env-id: ${{ vars.FD_ENV_ID }}

      - name: Run Cloudability Cost Estimation
        uses: IBM/ibm-cloudability-governance/actions/cost-estimation@v0.2.x
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          cloudability-host: ${{ vars.CLDY_HOST }}
          fd-env-id: ${{ vars.FD_ENV_ID }}
          deployment-name: "ahmad-cldy-test"
          project-name: "ahmad"
          provider-accounts: |
             {
              "module.database:aws_usw2": {
                "account_id": "${{ secrets.AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              },
              "*": {
                "account_id": "${{ secrets.SECOND_AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              }
            }
          tf-plan: "tfplan.json"
          resource-usage: ${{ steps.usage.outputs.USAGE_PATH }}

      - name: Run Cloudability Governance Policy Evaluation
        uses: IBM/ibm-cloudability-governance/actions/policy-evaluation@v0.2.x
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          cloudability-host: ${{ vars.CLDY_HOST }}
          fd-env-id: ${{ vars.FD_ENV_ID }}
          deployment-name: "ahmad-cldy-test"
          project-name: "ahmad"
          provider-accounts: |
             {
              "module.database:aws_usw2": {
                "account_id": "${{ secrets.AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              },
              "*": {
                "account_id": "${{ secrets.SECOND_AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              }
            }
          tf-plan: "tfplan.json"
          resource-usage: ${{ steps.usage.outputs.USAGE_PATH }}

      - name: Run Cloudability Recommendation
        uses: IBM/ibm-cloudability-governance/actions/recommendation@v0.2.x
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          cloudability-host: ${{ vars.CLDY_HOST }}
          fd-env-id: ${{ vars.FD_ENV_ID }}
          deployment-name: "ahmad-cldy-test"
          project-name: "ahmad"
          provider-accounts: |
            {
              "aws_usw2": {
                "account_id": "${{ secrets.AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              },
              "*": {
                "account_id": "${{ secrets.SECOND_AWS_ACCOUNT_ID }}", 
                "vendor": "aws"
              }
            }
          tf-plan: "tfplan.json"
          resource-usage: ${{ steps.usage.outputs.USAGE_PATH }}

# Made with Bob
